// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO_pTpuBGTQ-MNlya_kqULy9TeKrsg-ao',
    appId: '1:1009942221431:web:be2b83d2f72e1e95e0ac72',
    messagingSenderId: '1009942221431',
    projectId: 'broto-firebase-app',
    authDomain: 'broto-firebase-app.firebaseapp.com',
    storageBucket: 'broto-firebase-app.appspot.com',
    measurementId: 'G-52LFQHC7BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4FIU1Yg8lyJCancHVqgf7VgBVYjl-Cs',
    appId: '1:1009942221431:android:1cf55f99480436dae0ac72',
    messagingSenderId: '1009942221431',
    projectId: 'broto-firebase-app',
    storageBucket: 'broto-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZTbE0y0uIGX-wOvz1Qx2kXi5Rmye8944',
    appId: '1:1009942221431:ios:c5f8377dc03bef5fe0ac72',
    messagingSenderId: '1009942221431',
    projectId: 'broto-firebase-app',
    storageBucket: 'broto-firebase-app.appspot.com',
    iosBundleId: 'com.example.brototypeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZTbE0y0uIGX-wOvz1Qx2kXi5Rmye8944',
    appId: '1:1009942221431:ios:768f8317962016c5e0ac72',
    messagingSenderId: '1009942221431',
    projectId: 'broto-firebase-app',
    storageBucket: 'broto-firebase-app.appspot.com',
    iosBundleId: 'com.example.brototypeApp.RunnerTests',
  );
}
